// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PNT1_ProyectoFinal_Cine.Context;

namespace PNT1_ProyectoFinal_Cine.Migrations
{
    [DbContext(typeof(CineDatabaseContext))]
    partial class CineDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PNT1_ProyectoFinal_Cine.Models.Pelicula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Peliculas");
                });

            modelBuilder.Entity("PNT1_ProyectoFinal_Cine.Models.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cantAsientos")
                        .HasColumnType("int");

                    b.Property<int?>("peliculaAsignadaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("peliculaAsignadaId");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("PNT1_ProyectoFinal_Cine.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("asiento")
                        .HasColumnType("int");

                    b.Property<int?>("peliculaId")
                        .HasColumnType("int");

                    b.Property<int?>("salaId")
                        .HasColumnType("int");

                    b.Property<string>("usuarioNombreUsuario")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("peliculaId");

                    b.HasIndex("salaId");

                    b.HasIndex("usuarioNombreUsuario");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("PNT1_ProyectoFinal_Cine.Models.Usuario", b =>
                {
                    b.Property<string>("NombreUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Contrasenia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NombreUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PNT1_ProyectoFinal_Cine.Models.Sala", b =>
                {
                    b.HasOne("PNT1_ProyectoFinal_Cine.Models.Pelicula", "peliculaAsignada")
                        .WithMany()
                        .HasForeignKey("peliculaAsignadaId");
                });

            modelBuilder.Entity("PNT1_ProyectoFinal_Cine.Models.Ticket", b =>
                {
                    b.HasOne("PNT1_ProyectoFinal_Cine.Models.Pelicula", "pelicula")
                        .WithMany()
                        .HasForeignKey("peliculaId");

                    b.HasOne("PNT1_ProyectoFinal_Cine.Models.Sala", "sala")
                        .WithMany()
                        .HasForeignKey("salaId");

                    b.HasOne("PNT1_ProyectoFinal_Cine.Models.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioNombreUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
